server:
  port: 8081
spring:
  application:
    name: backendconfig-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Alexandra-Navarro/Mingeso_Microservicios
          search-paths: "Microservicios/config-data"
